# Generated by Django 3.2 on 2023-03-27 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Юзер не должен быть "me"', regex='^(?!me$)[\\w]+$'), django.core.validators.MinLengthValidator(5, message='Не менее 5 символов')], verbose_name='Имя пользователя'),
        ),
    ]
