# Generated by Django 3.2 on 2023-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230322_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка произведения'),
        ),
    ]
