# Generated by Django 3.2 on 2023-03-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_title_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
